### ISSUE TITLE
Softlock Freeze while in Garbage Wastes (Artificer)

### ISSUE THREAD

**Issue by dalekfan** [SchuhBaum/MapOptions#3]
https://pastebin.com/MDByk6Y1
Exception log here.

**Comment by SchuhBaum** [comment]
The function that crashes is a vanilla function (ItemMarker.Draw()). That should be related to the persistent item tracking (like tracking unique pearls and stuff). There are some vanilla issues with that. It should also not freeze your game since you need to keep the map open for it to happen.

That being said, it is not impossible that this mod causes it. But is seems somewhat unlikely.

**Comment by dalekfan** [comment]
> The function that crashes is a vanilla function (ItemMarker.Draw()). That should be related to the persistent item tracking (like tracking unique pearls and stuff). There are some vanilla issues with that. It should also not freeze your game since you need to keep the map open for it to happen.
> 
> That being said, it is not impossible that this mod causes it. But is seems somewhat unlikely.
[exceptionLog.txt](https://github.com/SchuhBaum/MapOptions/files/12225143/exceptionLog.txt)

Well I got it again if that helps. With less mods too.

**Comment by SchuhBaum** [comment]
Okay. You might need to provide additional information. See the section BUG REPORTS.

Maybe you can try to disable the mod and use the remix options 'SLUG SENSES' + 'KEY ITEM TRACKING' instead. This enables that the icons are drawn on the map with the MapOptions mod disabled. My suspicion is that this is a vanilla thing and you would encounter it in this case as well.
